name: Zig CI

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - engine: kiesel
            optimize: Debug
          - engine: quickjs
            optimize: Debug
          - engine: mquickjs
            optimize: ReleaseFast

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.16.0

    - name: Build
      run: zig build -Dengine=${{ matrix.engine }} -Doptimize=${{ matrix.optimize }}

    - name: Unit tests
      run: zig build test -Dengine=${{ matrix.engine }} -Doptimize=${{ matrix.optimize }}
